export const SCENE_LOGIN = 'LOGIN'
export const SCENE_SPLASH_SCREEN = 'SPLASH_SCREEN'
export const SCENE_HOME = 'HOME'
export const SCENE_PROFILE = 'PROFILE'
export const SCENE_LIBRARY = 'LIBRARY'
export const SCENE_SEARCH = 'SEARCH'
export const SCENE_LEARN = 'LEARN'
export const SCENE_REVIEW = 'REVIEW'
